@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Jun 26 14:24:31 -0700 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 10a816f5ebad46749ee52c437960a5ff --debug typical --mt 2 -L xil_defaultlib -L axi_bram_ctrl_v4_1_3 -L blk_mem_gen_v8_4_4 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_21 -L fifo_generator_v13_2_5 -L axi_data_fifo_v2_1_20 -L axi_crossbar_v2_1_22 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_core_top_wrapper_behav xil_defaultlib.tb_core_top_wrapper xil_defaultlib.glbl -log elaborate.log -v 1"
call xelab  -wto 10a816f5ebad46749ee52c437960a5ff --debug typical --mt 2 -L xil_defaultlib -L axi_bram_ctrl_v4_1_3 -L blk_mem_gen_v8_4_4 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_21 -L fifo_generator_v13_2_5 -L axi_data_fifo_v2_1_20 -L axi_crossbar_v2_1_22 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_core_top_wrapper_behav xil_defaultlib.tb_core_top_wrapper xil_defaultlib.glbl -log elaborate.log -v 1
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
