@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 24 16:06:53 -0800 2019
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb_core_top_wrapper_behav -key {Behavioral:sim_1:Functional:tb_core_top_wrapper} -tclbatch tb_core_top_wrapper.tcl -protoinst "protoinst_files/mc_top.protoinst" -protoinst "protoinst_files/jtag_to_axi.protoinst" -protoinst "protoinst_files/tb_core_top.protoinst" -view C:/Users/Benjamin/Documents/Word-documents/CPP/RISC-V-Multicore/src/test/do/tb_data_cache.wcfg -view C:/Users/Benjamin/Documents/Word-documents/CPP/RISC-V-Multicore/src/test/do/tb_core_top_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
