# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/9benj/Documents/GitHub/Reconfigurable-RISC-V/src/multicore_fpga/multicore_fpga.srcs/sources_1/bd/mc_top/ip/mc_top_data_mem_ctrl_0/mc_top_data_mem_ctrl_0.xci
# IP: The module: 'mc_top_data_mem_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/9benj/Documents/GitHub/Reconfigurable-RISC-V/src/multicore_fpga/multicore_fpga.srcs/sources_1/bd/mc_top/ip/mc_top_data_mem_ctrl_0/mc_top_data_mem_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mc_top_data_mem_ctrl_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/9benj/Documents/GitHub/Reconfigurable-RISC-V/src/multicore_fpga/multicore_fpga.srcs/sources_1/bd/mc_top/ip/mc_top_data_mem_ctrl_0/mc_top_data_mem_ctrl_0.xci
# IP: The module: 'mc_top_data_mem_ctrl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/9benj/Documents/GitHub/Reconfigurable-RISC-V/src/multicore_fpga/multicore_fpga.srcs/sources_1/bd/mc_top/ip/mc_top_data_mem_ctrl_0/mc_top_data_mem_ctrl_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mc_top_data_mem_ctrl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
