# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Benjamin/Documents/Word documents/CPP/RISC-V-Multicore/src/constraints/fpga.xdc

# Block Designs: bd/mc_top/mc_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc_top || ORIG_REF_NAME==mc_top} -quiet] -quiet

# IP: bd/mc_top/ip/mc_top_axi_interconnect_0/mc_top_axi_interconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc_top_axi_interconnect_0 || ORIG_REF_NAME==mc_top_axi_interconnect_0} -quiet] -quiet

# IP: bd/mc_top/ip/mc_top_reset_bridge_wrapper_0_0/mc_top_reset_bridge_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc_top_reset_bridge_wrapper_0_0 || ORIG_REF_NAME==mc_top_reset_bridge_wrapper_0_0} -quiet] -quiet

# IP: bd/mc_top/ip/mc_top_jtag_axi_0_0/mc_top_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc_top_jtag_axi_0_0 || ORIG_REF_NAME==mc_top_jtag_axi_0_0} -quiet] -quiet

# IP: bd/mc_top/ip/mc_top_inv_ff_0_0/mc_top_inv_ff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc_top_inv_ff_0_0 || ORIG_REF_NAME==mc_top_inv_ff_0_0} -quiet] -quiet

# IP: bd/mc_top/ip/mc_top_mig_7series_0_0/mc_top_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mc_top_mig_7series_0_0 || ORIG_REF_NAME==mc_top_mig_7series_0_0} -quiet] -quiet

# XDC: bd/mc_top/mc_top_ooc.xdc
