# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Benjamin/Documents/Word-documents/CPP/RISC-V-Multicore/src/multicore_fpga/multicore_fpga.srcs/sources_1/bd/jtag_to_axi/ip/jtag_to_axi_xbar_0/jtag_to_axi_xbar_0.xci
# IP: The module: 'jtag_to_axi_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Benjamin/Documents/Word-documents/CPP/RISC-V-Multicore/src/multicore_fpga/multicore_fpga.srcs/sources_1/bd/jtag_to_axi/ip/jtag_to_axi_xbar_0/jtag_to_axi_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_to_axi_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Benjamin/Documents/Word-documents/CPP/RISC-V-Multicore/src/multicore_fpga/multicore_fpga.srcs/sources_1/bd/jtag_to_axi/ip/jtag_to_axi_xbar_0/jtag_to_axi_xbar_0.xci
# IP: The module: 'jtag_to_axi_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Benjamin/Documents/Word-documents/CPP/RISC-V-Multicore/src/multicore_fpga/multicore_fpga.srcs/sources_1/bd/jtag_to_axi/ip/jtag_to_axi_xbar_0/jtag_to_axi_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_to_axi_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
